### PR TITLE
Minor cleanup for code case consistency, spaces at EOL.

### PR DESCRIPTION
**Pull request by StevenBlack**
Signed-off-by: Steven Black steveb@stevenblack.com

### CODE REVIEW

**Comment by FoxInCloud** [comment]
OK I will try the VFPx beautify tool

**Comment by FoxInCloud** [comment]
I get lost in conflicts, I'll see this again tomorrow - a lot of tools to get a hold on fast

**Comment by StevenBlack** [comment]
This will help.  A lot.

http://ndpsoftware.com/git-cheatsheet.html

**Comment by FoxInCloud** [comment]
thanks Steve, I'll check this out tomorrow; it's a pleasure to have you jump into this project.

**Comment by FoxInCloud** [comment]
I had misunderstood "Remove, .gitignore, .err and .fxp files " - thought .gitignore had to be 'removed' instead of 'modified' as you meant.
Could revert my commit so we should be back to normal

**Comment by FoxInCloud** [comment]
VFP's beautify sucks a little because, even if you disable 'indentation', it moves all '*' comments to the left margin, which I dislike

**Comment by FoxInCloud** [comment]
Did the same changes myself (was in a mess), closing this pull request

**Comment by FoxInCloud** [comment]
please try another pull request that I can practice on - thanks

**Pull request closed without merging**
